replicaCount: 3
image:
  repository: scylladb/scylla
  tag: 5.2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9042
resources: {}

persistence:
  enabled: true
  size: 500Gi
  storageClass: fast-disks

networkPolicy:
  enabled: true
  allowedNamespaces:
    - "default"
    - "analytics"
