{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "scylla.fullname" . }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ include "scylla.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.allowedNamespaces | first }}
  egress:
    - to:
        - namespaceSelector: {}
{{- end }}
